# Generated by Django 2.1 on 2019-09-08 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_view_goldpage', 'Can View Goldpage')]},
        ),
    ]
